docker run -it \
	-e POSTGRES_USER="root" \
	-e POSTGRES_PASSWORD="root" \
	-e POSTGRES_DB="ny_taxi" \
	-v x:\home\serge\ny_taxi_postgers_data:/var/lib/postgresql/data \
	-p 5432:5432 \
	postgres:13

